# Generated by Django 2.0.7 on 2018-09-29 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Module_TeamManagement', '0003_course_section_to_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWS_Credentials',
            fields=[
                ('account_number', models.CharField(db_column='AccountNumber', max_length=255, primary_key=True, serialize=False)),
                ('access_key', models.TextField(db_column='Access_Key')),
                ('secret_access_key', models.TextField(db_column='Secret_Access_Key')),
                ('faculty', models.ForeignKey(db_column='Faculty', on_delete=django.db.models.deletion.CASCADE, to='Module_TeamManagement.Faculty')),
            ],
            options={
                'db_table': 'AWS_Credentials',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Deployment_Package',
            fields=[
                ('deploymentid', models.CharField(db_column='Deployment ID', max_length=255, primary_key=True, serialize=False)),
                ('gitlink', models.CharField(db_column='Git Hub Link', max_length=255)),
            ],
            options={
                'db_table': 'Deployment_Package',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Image_Details',
            fields=[
                ('imageid', models.CharField(db_column='Image_ID', max_length=255, primary_key=True, serialize=False)),
                ('imagename', models.CharField(db_column='Image Name', max_length=255)),
                ('sharedAccNum', models.TextField(db_column='List of shared account number')),
            ],
            options={
                'db_table': 'Image_Details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Server_Details',
            fields=[
                ('IP_address', models.CharField(db_column='IP_Address', max_length=255, primary_key=True, serialize=False)),
                ('instanceid', models.CharField(db_column='Instance_ID', max_length=255)),
                ('instanceName', models.CharField(db_column='Instance Name', max_length=255)),
                ('state', models.CharField(db_column='Server State', max_length=255, null=True)),
                ('credentials', models.ForeignKey(db_column='AWS Credential linked', null=True, on_delete=django.db.models.deletion.CASCADE, to='Module_DeploymentMonitoring.AWS_Credentials')),
            ],
            options={
                'db_table': 'Server_Details',
                'managed': True,
            },
        ),
    ]
