# Generated by Django 2.0.7 on 2018-09-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('instance_id', models.CharField(db_column='Instance_ID', max_length=255, primary_key=True, serialize=False)),
                ('allocation_id', models.CharField(db_column='Allocation_ID', max_length=255, null=True)),
                ('public_ip', models.CharField(db_column='Public_Ip', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Server',
                'managed': True,
            },
        ),
    ]
