# Generated by Django 2.0.7 on 2018-10-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module_DeploymentMonitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server_details',
            name='type',
            field=models.CharField(choices=[('Parent', 'Parent'), ('Slave', 'Slave')], db_column='Server_Type', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='server_details',
            name='state',
            field=models.CharField(choices=[('Live', 'Live'), ('Pending', 'Pending'), ('Down', 'Down')], db_column='Server_State', max_length=255, null=True),
        ),
    ]
