# Generated by Django 2.0.7 on 2018-09-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module_DeploymentMonitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elastic_IPs',
            fields=[
                ('allocation_id', models.CharField(db_column='Allocation_ID', max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Elastic_IPs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('instance_id', models.CharField(db_column='Instance_ID', max_length=255, primary_key=True, serialize=False)),
                ('public_ip', models.CharField(db_column='Public_IP', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Instance',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Server',
        ),
    ]
