# Generated by Django 2.0.7 on 2018-09-29 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Module_DeploymentMonitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_details',
            old_name='imageid',
            new_name='imageId',
        ),
        migrations.RemoveField(
            model_name='aws_credentials',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='image_details',
            name='imagename',
        ),
        migrations.RemoveField(
            model_name='server_details',
            name='credentials',
        ),
        migrations.AddField(
            model_name='aws_credentials',
            name='imageDetails',
            field=models.ForeignKey(db_column='Image_Details', null=True, on_delete=django.db.models.deletion.CASCADE, to='Module_DeploymentMonitoring.Image_Details'),
        ),
        migrations.AddField(
            model_name='aws_credentials',
            name='serverDetails',
            field=models.ForeignKey(db_column='Server_Details', null=True, on_delete=django.db.models.deletion.CASCADE, to='Module_DeploymentMonitoring.Server_Details'),
        ),
        migrations.AddField(
            model_name='image_details',
            name='imageName',
            field=models.CharField(db_column='Image_Name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image_details',
            name='sharedAccNum',
            field=models.TextField(db_column='List_of_shared_account_number'),
        ),
        migrations.AlterField(
            model_name='server_details',
            name='instanceName',
            field=models.CharField(db_column='Instance_Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='server_details',
            name='state',
            field=models.CharField(db_column='Server_State', max_length=255, null=True),
        ),
    ]
