# Generated by Django 2.0.7 on 2018-10-25 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Module_DeploymentMonitoring', '0002_auto_20181019_0902'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deployment_Package',
        ),
    ]
