# Generated by Django 2.0.7 on 2018-10-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module_DeploymentMonitoring', '0002_auto_20180929_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aws_credentials',
            name='access_key',
            field=models.TextField(db_column='Access_Key', null=True),
        ),
        migrations.AlterField(
            model_name='aws_credentials',
            name='secret_access_key',
            field=models.TextField(db_column='Secret_Access_Key', null=True),
        ),
        migrations.AlterField(
            model_name='image_details',
            name='sharedAccNum',
            field=models.TextField(db_column='List_of_shared_account_number', null=True),
        ),
    ]
