# Generated by Django 2.0.7 on 2018-10-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module_DeploymentMonitoring', '0003_auto_20181002_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_details',
            name='instanceName',
            field=models.CharField(db_column='Instance_Name', max_length=255, null=True),
        ),
    ]
