# Generated by Django 2.0.7 on 2018-11-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module_TeamManagement', '0019_remove_course_section_deployment_package'),
        ('Module_DeploymentMonitoring', '0004_deployment_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment_package',
            name='course_section',
            field=models.ManyToManyField(db_column='Course_Section', null=True, to='Module_TeamManagement.Course_Section'),
        ),
    ]
