# Generated by Django 2.0.7 on 2018-10-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module_DeploymentMonitoring', '0004_auto_20181002_0439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aws_credentials',
            name='imageDetails',
        ),
        migrations.AddField(
            model_name='aws_credentials',
            name='imageDetails',
            field=models.ManyToManyField(db_column='Image_Details', null=True, to='Module_DeploymentMonitoring.Image_Details'),
        ),
    ]
