# Generated by Django 2.0.7 on 2018-10-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module_DeploymentMonitoring', '0005_auto_20181002_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment_package',
            name='deploymentid',
            field=models.CharField(db_column='Deployment_ID', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deployment_package',
            name='gitlink',
            field=models.CharField(db_column='GitHub_Link', max_length=255),
        ),
    ]
