# Generated by Django 2.0.7 on 2018-11-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module_DeploymentMonitoring', '0005_deployment_package_course_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment_package',
            name='shared_sections',
            field=models.TextField(db_column='Shared_Sections', null=True),
        ),
    ]
