# Generated by Django 2.0.7 on 2018-10-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module_DeploymentMonitoring', '0006_auto_20181002_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment_package',
            name='gitlink',
            field=models.TextField(db_column='GitHub_Link'),
        ),
    ]
