# Generated by Django 2.0.7 on 2018-10-03 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Module_DeploymentMonitoring', '0007_auto_20181002_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aws_credentials',
            name='serverDetails',
        ),
        migrations.AddField(
            model_name='server_details',
            name='account_number',
            field=models.ForeignKey(db_column='AWS_Account_Number', null=True, on_delete=django.db.models.deletion.CASCADE, to='Module_DeploymentMonitoring.AWS_Credentials'),
        ),
        migrations.AlterField(
            model_name='aws_credentials',
            name='account_number',
            field=models.CharField(db_column='Account_Number', max_length=255, primary_key=True, serialize=False),
        ),
    ]
