# Generated by Django 2.0.7 on 2018-07-30 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('email', models.EmailField(db_column='Instructor_Email', max_length=254, primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=255)),
                ('firstname', models.CharField(db_column='Firstname', max_length=255)),
                ('lastname', models.CharField(db_column='Lastname', max_length=255)),
                ('telegram_username', models.CharField(db_column='Instructor_Telegram_Username', max_length=255, null=True)),
                ('phone_number', models.IntegerField(db_column='Phone_Number', null=True)),
            ],
            options={
                'db_table': 'Instructor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_number', models.CharField(db_column='Section_Number', max_length=2, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Section',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('email', models.EmailField(db_column='Student_Email', max_length=254, primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=255)),
                ('firstname', models.CharField(db_column='Firstname', max_length=255)),
                ('lastname', models.CharField(db_column='Lastname', max_length=255)),
                ('telegram_username', models.CharField(db_column='Student_Telegram_Username', max_length=255, null=True)),
                ('grades', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('F', 'F')], db_column='Student_Grades', max_length=2, null=True)),
                ('marks', models.IntegerField(db_column='Student_Marks', null=True)),
                ('phone_number', models.IntegerField(db_column='Phone_Number', null=True)),
            ],
            options={
                'db_table': 'Student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Teaching_Assistant',
            fields=[
                ('email', models.EmailField(db_column='Teaching_Assistant_Email', max_length=254, primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=255)),
                ('firstname', models.CharField(db_column='Firstname', max_length=255)),
                ('lastname', models.CharField(db_column='Lastname', max_length=255)),
                ('telegram_username', models.CharField(db_column='TA_Telegram_Username', max_length=255, null=True)),
                ('phone_number', models.IntegerField(db_column='Phone_Number', null=True)),
                ('section', models.ForeignKey(db_column='Section', default='G0', on_delete=django.db.models.deletion.CASCADE, to='Module_TeamManagement.Section')),
            ],
            options={
                'db_table': 'Teaching_Assistant',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Assigned_Team',
            fields=[
                ('student', models.OneToOneField(db_column='Student', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Module_TeamManagement.Student')),
                ('team_number', models.CharField(db_column='Team_Number', default='T0', max_length=2)),
                ('section', models.ForeignKey(db_column='Section', default='G0', on_delete=django.db.models.deletion.CASCADE, to='Module_TeamManagement.Section')),
            ],
            options={
                'db_table': 'Assigned_Team',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='instructor',
            name='section',
            field=models.ManyToManyField(db_column='Section', to='Module_TeamManagement.Section'),
        ),
    ]
