# Generated by Django 2.0.7 on 2018-07-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module_TeamManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.IntegerField(db_column='Phone_Number', null=True),
        ),
        migrations.AddField(
            model_name='teaching_assistant',
            name='phone_number',
            field=models.IntegerField(db_column='Phone_Number', null=True),
        ),
    ]
