# Generated by Django 2.0.7 on 2018-07-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module_TeamManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='phone_number',
            field=models.CharField(db_column='Phone_Number', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(db_column='Phone_Number', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teaching_assistant',
            name='phone_number',
            field=models.CharField(db_column='Phone_Number', max_length=10, null=True),
        ),
    ]
