# Generated by Django 2.0.7 on 2018-08-07 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Module_TeamManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud_Learning_Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_column='Type', max_length=255)),
                ('website_link', models.TextField(db_column='Website_Link')),
                ('student', models.ForeignKey(db_column='Student', on_delete=django.db.models.deletion.CASCADE, to='Module_TeamManagement.Student')),
            ],
            options={
                'db_table': 'Cloud_Learning_Tools',
                'managed': True,
            },
        ),
    ]
