# Generated by Django 2.0.7 on 2018-09-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module_TeamManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_section',
            name='learning_tools',
            field=models.TextField(db_column='Course_Section_Learning_Tools_List', null=True),
        ),
    ]
