# Generated by Django 2.0.7 on 2018-09-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module_TeamManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='loginCounts',
            field=models.IntegerField(db_column='Number_of_Logins', default=0),
        ),
    ]
