# Generated by Django 2.0.7 on 2018-08-09 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Module_TeamManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='clt_id',
            field=models.ForeignKey(db_column='CLT_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='Module_TeamManagement.Cloud_Learning_Tools'),
        ),
    ]
