# Generated by Django 2.0.7 on 2018-08-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module_TeamManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='phone_number',
            field=models.CharField(db_column='Phone_Number', max_length=255, null=True),
        ),
    ]
