# Generated by Django 2.0.7 on 2018-08-27 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Module_TeamManagement', '0002_auto_20180825_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_Term',
            fields=[
                ('school_term_id', models.CharField(db_column='School_Term_ID', max_length=255, primary_key=True, serialize=False)),
                ('term', models.CharField(db_column='Term', max_length=255)),
                ('financial_year', models.CharField(db_column='Financial_Year', max_length=255)),
                ('start_date', models.DateField(db_column='Start_Date')),
                ('end_date', models.DateField(db_column='End_Date')),
            ],
            options={
                'db_table': 'School_Term',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='school_term',
            unique_together={('financial_year', 'term')},
        ),
        migrations.AddField(
            model_name='class',
            name='school_term',
            field=models.ForeignKey(db_column='School_Term', default=None, on_delete=django.db.models.deletion.CASCADE, to='Module_TeamManagement.School_Term'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('student', 'course_section', 'school_term')},
        ),
    ]
