# Generated by Django 2.0.7 on 2018-08-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module_TeamManagement', '0002_auto_20180809_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.TextField(db_column='Course_Description', null=True),
        ),
    ]
