# Generated by Django 2.0.7 on 2018-09-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module_TeamManagement', '0002_course_section_learning_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='loginCounts',
            field=models.IntegerField(db_column='Number of Logins', default=0),
        ),
    ]
