# Generated by Django 2.0.7 on 2018-09-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module_TeamManagement', '0002_auto_20180913_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_section',
            name='to_string',
            field=models.CharField(db_column='To_String', max_length=255, null=True),
        ),
    ]
