# Generated by Django 2.0.7 on 2018-08-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module_TeamManagement', '0003_auto_20180811_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloud_learning_tools',
            name='id',
            field=models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False),
        ),
    ]
