# Generated by Django 2.0.7 on 2018-10-04 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Module_DeploymentMonitoring', '0001_initial'),
        ('Module_TeamManagement', '0003_course_section_to_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='awscredential',
            field=models.ForeignKey(db_column='AWS_Credentials', null=True, on_delete=django.db.models.deletion.CASCADE, to='Module_DeploymentMonitoring.AWS_Credentials'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='awscredential',
            field=models.ForeignKey(db_column='AWS_Credentials', null=True, on_delete=django.db.models.deletion.CASCADE, to='Module_DeploymentMonitoring.AWS_Credentials'),
        ),
    ]
