# Generated by Django 2.0.7 on 2018-10-17 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Module_TeamManagement', '0004_auto_20181005_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trailmix_Information',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=255, primary_key=True, serialize=False)),
                ('link', models.TextField(db_column='Link')),
                ('description', models.TextField(db_column='Description', null=True)),
                ('badges', models.TextField(db_column='Badges', null=True)),
                ('course', models.ForeignKey(db_column='Course', on_delete=django.db.models.deletion.CASCADE, to='Module_TeamManagement.Course')),
            ],
            options={
                'db_table': 'Trailmix_Information',
                'managed': True,
            },
        ),
    ]
