# Generated by Django 2.0.7 on 2018-10-17 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Module_TeamManagement', '0005_trailmix_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloud_learning_tools',
            name='course_section',
            field=models.ForeignKey(db_column='Course_Section', null=True, on_delete=django.db.models.deletion.CASCADE, to='Module_TeamManagement.Course_Section'),
        ),
    ]
