# Generated by Django 2.0.7 on 2018-10-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module_TeamManagement', '0006_cloud_learning_tools_course_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram_Tools',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('type', models.CharField(choices=[('Channel', 'Channel'), ('Group', 'Group')], db_column='Type', max_length=10)),
                ('link', models.TextField(db_column='Link')),
                ('members', models.TextField(db_column='Members')),
            ],
            options={
                'db_table': 'Telegram_Tools',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='class',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='class',
            name='score',
        ),
        migrations.RemoveField(
            model_name='class',
            name='telegram_channellink',
        ),
        migrations.RemoveField(
            model_name='class',
            name='telegram_grouplink',
        ),
        migrations.AddField(
            model_name='class',
            name='telegram_tools',
            field=models.ManyToManyField(db_column='Telegram_Tools', null=True, to='Module_TeamManagement.Telegram_Tools'),
        ),
    ]
