# Generated by Django 2.0.7 on 2018-10-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module_TeamManagement', '0007_auto_20181026_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram_tools',
            name='members',
            field=models.TextField(db_column='Members', null=True),
        ),
    ]
