# Generated by Django 2.0.7 on 2018-10-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Module_TeamManagement', '0008_auto_20181026_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='telegram_tools',
        ),
        migrations.DeleteModel(
            name='Telegram_Tools',
        ),
    ]
