# Generated by Django 2.0.7 on 2018-10-26 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Module_TeamManagement', '0010_auto_20181026_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='telegram_tools',
            new_name='telegram_chats',
        ),
    ]
