# Generated by Django 2.0.7 on 2018-11-08 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Module_TeamManagement', '0011_auto_20181026_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailmix_information',
            name='course',
        ),
        migrations.DeleteModel(
            name='Trailmix_Information',
        ),
    ]
