# Generated by Django 2.0.7 on 2018-11-08 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Module_TeamManagement', '0012_auto_20181108_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trailmix_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=255, null=True)),
                ('link', models.TextField(db_column='Link', null=True)),
                ('description', models.TextField(db_column='Description', null=True)),
                ('badges', models.TextField(db_column='Badges', null=True)),
                ('course', models.ForeignKey(db_column='Course', null=True, on_delete=django.db.models.deletion.CASCADE, to='Module_TeamManagement.Course')),
            ],
            options={
                'db_table': 'Trailmix_Information',
                'managed': True,
            },
        ),
    ]
