# Generated by Django 2.0.7 on 2018-11-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module_DeploymentMonitoring', '0004_deployment_package'),
        ('Module_TeamManagement', '0017_auto_20181114_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_section',
            name='deployment_package',
            field=models.ManyToManyField(db_column='Deployment_Package', null=True, to='Module_DeploymentMonitoring.Deployment_Package'),
        ),
        migrations.AddField(
            model_name='trailmix_information',
            name='course_sections',
            field=models.TextField(db_column='Course_Sections_Details', null=True),
        ),
    ]
