# Generated by Django 2.0.7 on 2018-11-20 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Module_TeamManagement', '0018_auto_20181120_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_section',
            name='deployment_package',
        ),
    ]
