# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('email', models.EmailField(db_column='Instructor_Email', max_length=254, primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=255)),
                ('firstname', models.CharField(db_column='Firstname', max_length=255)),
                ('lastname', models.CharField(db_column='Lastname', max_length=255)),
                ('password', models.CharField(db_column='Password', max_length=255)),
            ],
            options={
                'db_table': 'Instructor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_number', models.CharField(db_column='Section_Number', max_length=2, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Section',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('email', models.EmailField(db_column='Student_Email', max_length=254, primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=255)),
                ('firstname', models.CharField(db_column='Firstname', max_length=255)),
                ('lastname', models.CharField(db_column='Lastname', max_length=255)),
                ('password', models.CharField(db_column='Password', max_length=255)),
            ],
            options={
                'db_table': 'Student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Assigned_Team',
            fields=[
                ('student_email', models.ForeignKey(db_column='Student_Email', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Module_TeamManagement.Student')),
                ('team_number', models.CharField(db_column='Team_Number', max_length=2)),
                ('section_number', models.ForeignKey(db_column='Section_Number', on_delete=django.db.models.deletion.CASCADE, to='Module_TeamManagement.Section')),
            ],
            options={
                'db_table': 'Assigned_Team',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='instructor',
            name='section_number',
            field=models.ManyToManyField(db_column='Section_Number', null=True, to='Module_TeamManagement.Section'),
        ),
    ]
