# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Module_TeamManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigned_team',
            name='section_number',
        ),
        migrations.RemoveField(
            model_name='assigned_team',
            name='student_email',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='section_number',
        ),
        migrations.AddField(
            model_name='assigned_team',
            name='section',
            field=models.ForeignKey(db_column='Section', default='G0', on_delete=django.db.models.deletion.CASCADE, to='Module_TeamManagement.Section'),
        ),
        migrations.AddField(
            model_name='assigned_team',
            name='student',
            field=models.OneToOneField(db_column='Student', default='NULL', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Module_TeamManagement.Student'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='section',
            field=models.ManyToManyField(db_column='Section', null=True, to='Module_TeamManagement.Section'),
        ),
        migrations.AlterField(
            model_name='assigned_team',
            name='team_number',
            field=models.CharField(choices=[('T1', 'Team 1'), ('T2', 'Team 2'), ('T3', 'Team 3'), ('T4', 'Team 4'), ('T5', 'Team 5'), ('T6', 'Team 6'), ('T7', 'Team 7'), ('T8', 'Team 8'), ('T9', 'Team 9'), ('T10', 'Team 10')], db_column='Team_Number', default='T0', max_length=2),
        ),
    ]
