# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module_TeamManagement', '0002_auto_20180626_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned_team',
            name='team_number',
            field=models.CharField(choices=[('Team 1', 'T1'), ('Team 2', 'T2'), ('Team 3', 'T3'), ('Team 4', 'T4'), ('T5', 'Team 5'), ('T6', 'Team 6'), ('T7', 'Team 7'), ('T8', 'Team 8'), ('T9', 'Team 9'), ('T10', 'Team 10')], db_column='Team_Number', default='T0', max_length=2),
        ),
    ]
