# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module_TeamManagement', '0003_auto_20180626_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned_team',
            name='team_number',
            field=models.CharField(db_column='Team_Number', max_length=6),
        ),
    ]
